# Import Dependencies

In [1]:
import numpy as np
import pandas as pd

# Read in Data

In [2]:
geodist_long_CS= pd.read_csv("SEDA_geodist_long_CS_v21.csv")

# Exploratory Data Analysis

## All data
Check out the columns in the dataset, describe the dataset, etc

In [3]:
geodist_long_CS.columns

Index(['leaidC', 'leaname', 'fips', 'stateabb', 'grade', 'year', 'subject',
       'totgyb_all', 'mn_all', 'mn_all_se', 'sd_all', 'sd_all_se',
       'totgyb_asn', 'mn_asn', 'mn_asn_se', 'sd_asn', 'sd_asn_se',
       'totgyb_blk', 'mn_blk', 'mn_blk_se', 'sd_blk', 'sd_blk_se',
       'totgyb_fem', 'mn_fem', 'mn_fem_se', 'sd_fem', 'sd_fem_se',
       'totgyb_hsp', 'mn_hsp', 'mn_hsp_se', 'sd_hsp', 'sd_hsp_se',
       'totgyb_mal', 'mn_mal', 'mn_mal_se', 'sd_mal', 'sd_mal_se',
       'totgyb_wht', 'mn_wht', 'mn_wht_se', 'sd_wht', 'sd_wht_se', 'mn_wag',
       'mn_wag_se', 'mn_wbg', 'mn_wbg_se', 'mn_whg', 'mn_whg_se', 'mn_mfg',
       'mn_mfg_se'],
      dtype='object')

In [4]:
# Assign names of quantitative columns for later use

quant_cols= ['totgyb_all', 'mn_all', 'mn_all_se', 'sd_all', 'sd_all_se',
       'totgyb_asn', 'mn_asn', 'mn_asn_se', 'sd_asn', 'sd_asn_se',
       'totgyb_blk', 'mn_blk', 'mn_blk_se', 'sd_blk', 'sd_blk_se',
       'totgyb_fem', 'mn_fem', 'mn_fem_se', 'sd_fem', 'sd_fem_se',
       'totgyb_hsp', 'mn_hsp', 'mn_hsp_se', 'sd_hsp', 'sd_hsp_se',
       'totgyb_mal', 'mn_mal', 'mn_mal_se', 'sd_mal', 'sd_mal_se',
       'totgyb_wht', 'mn_wht', 'mn_wht_se', 'sd_wht', 'sd_wht_se', 'mn_wag',
       'mn_wag_se', 'mn_wbg', 'mn_wbg_se', 'mn_whg', 'mn_whg_se', 'mn_mfg',
       'mn_mfg_se']

### 825816 Rows

In [5]:
print(len(geodist_long_CS))

825816

In [6]:
desc_geodist_long_CS= geodist_long_CS.describe()

The total number of observations in this data set is __825816__ (see above), but the White-Asian-Gap *(wag)* has only 84024 valid values (see below). In an attempt to adjust for this, I removed all invalid *(NaN)* values, but this resulted in VT falling out of the resulting dataset (see *DropNA (ANY)*). When I dropped ALL NA values, this maintained all 825816 rows.

In [7]:
print(desc_geodist_long_CS.loc["count",:].min())
print("*"*20)
print(desc_geodist_long_CS.loc["count",:].sort_values())

84024.0
********************
mn_wag         84024.0
mn_wag_se      84024.0
mn_asn_se      85523.0
sd_asn_se      85523.0
sd_asn         85523.0
totgyb_asn     85523.0
mn_asn         85523.0
mn_wbg_se     164413.0
mn_wbg        164413.0
totgyb_blk    183171.0
mn_blk        183171.0
mn_blk_se     183171.0
sd_blk        183171.0
sd_blk_se     183171.0
mn_whg        196243.0
mn_whg_se     196243.0
sd_hsp_se     222124.0
sd_hsp        222124.0
mn_hsp_se     222124.0
totgyb_hsp    222124.0
mn_hsp        222124.0
mn_mfg_se     658277.0
mn_mfg        658277.0
sd_fem_se     684574.0
mn_fem_se     684574.0
mn_fem        684574.0
totgyb_fem    684574.0
sd_fem        684574.0
sd_mal        695481.0
sd_mal_se     695481.0
totgyb_mal    695482.0
mn_mal        695482.0
mn_mal_se     695482.0
sd_wht_se     733460.0
sd_wht        733460.0
mn_wht_se     733460.0
mn_wht        733460.0
totgyb_wht    733460.0
sd_all        825814.0
sd_all_se     825814.0
mn_all_se     825814.0
mn_all        825814.0
totgyb_all    825814.0
year          825816.0
grade         825816.0
fips          825816.0
leaidC        825816.0
Name: count, dtype: float64

In [8]:
print(len(geodist_long_CS["stateabb"].value_counts()))
print(geodist_long_CS["stateabb"].value_counts().sort_index())

51
AK     2601
AL    10989
AR    18426
AZ    12056
CA    45425
CO     4619
CT    10742
DC       82
DE     1299
FL     5336
GA    15035
HI       84
IA    25245
ID     6159
IL    56071
IN    24082
KS    16040
KY    14284
LA     6084
MA    20854
MD     1845
ME     8823
MI    41408
MN    25410
MO    31020
MS    11811
MT     6132
NC     9680
ND     4767
NE    10265
NH     9226
NJ    32655
NM     5587
NV      916
NY    40473
OH    49847
OK    29408
OR    10411
PA    41698
RI     2536
SC     7046
SD     6696
TN    11041
TX    63016
UT     3002
VA     7360
VT     7441
WA    12916
WI    31639
WV     4372
WY     1856
Name: stateabb, dtype: int64

In [9]:
geodist_long_CS.head()

,leaidC,leaname,fips,stateabb,grade,year,subject,totgyb_all,mn_all,mn_all_se,...,sd_wht,sd_wht_se,mn_wag,mn_wag_se,mn_wbg,mn_wbg_se,mn_whg,mn_whg_se,mn_mfg,mn_mfg_se
0,100002,Alabama Youth Services,1,AL,8,2009,ela,29.0,-1.569190,0.209354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,Alabama Youth Services,1,AL,8,2009,math,36.0,-1.761643,0.206164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100002,Alabama Youth Services,1,AL,8,2011,ela,29.0,-0.962804,0.203069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100002,Alabama Youth Services,1,AL,8,2011,math,27.0,-1.641117,0.223450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100002,Alabama Youth Services,1,AL,8,2012,ela,33.0,-1.069076,0.190945,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

4th grade is most represented, 8th grade is least represented. Consult documentation for reasons as to why (possibly students being held back and so unaccounted for in 8th grade counts?)

In [10]:
geodist_long_CS["grade"].value_counts()

4    142137
3    141849
5    141504
6    140408
7    131720
8    128198
Name: grade, dtype: int64

Schools grouped together and average values for all rows calculated.

In [11]:
leaname_gb= geodist_long_CS.groupby("leaname")

leaname_gb.mean()

,leaidC,fips,grade,year,totgyb_all,mn_all,mn_all_se,sd_all,sd_all_se,totgyb_asn,...,sd_wht,sd_wht_se,mn_wag,mn_wag_se,mn_wbg,mn_wbg_se,mn_whg,mn_whg_se,mn_mfg,mn_mfg_se
leaname,,,,,,,,,,,,,,,,,,,,,
A-C Central Cusd 262,1700105.0,17.0,5.481928,2011.963855,34.349398,-0.038868,0.184465,0.884512,0.014171,NaN,...,0.878956,0.014433,NaN,NaN,NaN,NaN,NaN,NaN,-0.263950,0.326949
A-H-S-T Comm School District,1904080.0,19.0,5.500000,2012.000000,43.714286,0.097133,0.163362,0.872643,0.060888,NaN,...,0.856911,0.042866,NaN,NaN,NaN,NaN,NaN,NaN,-0.118130,0.298586
A.C.G.C.,2700106.0,27.0,5.500000,2012.000000,60.559524,0.187885,0.128547,0.812506,0.117710,NaN,...,0.813022,0.113667,NaN,NaN,NaN,NaN,NaN,NaN,-0.003366,0.271886
A.E. Phillips Laboratory School,2200056.0,22.0,5.500000,2012.000000,38.595238,0.998903,0.169973,0.825322,0.046300,NaN,...,0.848939,0.016911,NaN,NaN,NaN,NaN,NaN,NaN,-0.189476,0.290548
Abbeville 60,4500690.0,45.0,5.500000,2012.000000,246.964286,0.137747,0.089601,0.949825,0.090067,NaN,...,0.950259,0.130460,NaN,NaN,0.604337,0.181694,NaN,NaN,-0.161140,0.180527
Abbotsford School District,5500030.0,55.0,5.500000,2012.000000,48.297619,-0.067550,0.149458,0.853007,0.076916,NaN,...,0.857250,0.015697,NaN,NaN,NaN,NaN,0.640977,0.285144,-0.102699,0.289086
Abbott Isd,4807380.0,48.0,5.406780,2011.576271,22.966102,0.240497,0.247496,0.867472,0.016617,NaN,...,0.848594,0.015628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abc Unified,601620.0,6.0,5.177419,2011.774194,1536.564516,0.099762,0.048817,1.114203,0.041806,564.437500,...,0.974575,0.119874,-0.653487,0.145913,0.421655,0.154147,0.517795,0.129620,-0.134685,0.084091
Aberdeen District,1600030.0,16.0,5.500000,2011.666667,59.041667,-0.318623,0.134911,0.837390,0.121965,NaN,...,0.876491,0.019740,NaN,NaN,NaN,NaN,0.654563,0.271893,0.144401,0.279572
Aberdeen School Dist,2800360.0,28.0,5.392405,2011.860759,101.303797,-0.695376,0.102911,0.827869,0.099053,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.265382,0.200453
Aberdeen School District,5300030.0,53.0,5.500000,2011.000000,234.100000,-0.221585,0.078232,0.961074,0.081115,NaN,...,0.964098,0.102546,NaN,NaN,NaN,NaN,0.368711,0.175640,-0.177456,0.152217
Aberdeen School District 06-1,4602070.0,46.0,5.500000,2011.666667,302.875000,0.192126,0.059658,0.843767,0.056018,NaN,...,0.835932,0.060248,NaN,NaN,NaN,NaN,NaN,NaN,-0.091766,0.117449
Abernathy Isd,4807410.0,48.0,5.289474,2011.842105,58.236842,-0.064006,0.153980,0.870454,0.113355,NaN,...,0.848030,0.017550,NaN,NaN,NaN,NaN,0.567422,0.304711,-0.009289,0.310320
Abilene,2003180.0,20.0,5.500000,2011.666667,117.361111,0.155584,0.083976,0.738561,0.074896,NaN,...,0.738153,0.079529,NaN,NaN,NaN,NaN,NaN,NaN,-0.003353,0.162694
Abilene Isd,4807440.0,48.0,5.289474,2011.842105,1224.500000,-0.051369,0.044342,0.919495,0.034275,25.846154,...,0.900725,0.050554,0.053618,0.268242,0.557140,0.116409,0.383582,0.084181,-0.058464,0.079767
Abingdon Cusd 217,1703090.0,17.0,5.500000,2011.000000,53.483333,-0.056182,0.144993,0.833664,0.081819,NaN,...,0.853187,0.054071,NaN,NaN,NaN,NaN,NaN,NaN,-0.052293,0.301088
Abingdon-Avon Cusd 276,1701413.0,17.0,5.500000,2014.500000,68.958333,-0.239653,0.118255,0.802489,0.103922,NaN,...,0.813331,0.099981,NaN,NaN,NaN,NaN,NaN,NaN,0.008696,0.249742
Abington,2501650.0,25.0,5.500000,2012.000000,172.023810,0.348277,0.079314,0.834116,0.070000,NaN,...,0.827842,0.072236,NaN,NaN,NaN,NaN,NaN,NaN,-0.230002,0.153702
Abington Sd,4202040.0,42.0,5.500000,2012.000000,560.428571,0.538374,0.063496,0.876996,0.057767,28.675000,...,0.854321,0.075566,-0.205725,0.272674,0.670642,0.126698,0.382475,0.203722,-0.135630,0.119434
Abington Heights Sd,4202010.0,42.0,5.500000,2012.000000,256.952381,0.549612,0.090531,0.873831,0.085502,21.000000,...,0.860064,0.087542,-0.391718,0.275318,NaN,NaN,NaN,NaN,-0.120070,0.178642
Absarokee Elem,3001710.0,30.0,5.575758,2010.636364,23.848485,0.002106,0.204796,0.827010,0.016898,NaN,...,0.820275,0.020586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Absecon City,3400660.0,34.0,5.500000,2011.500000,91.458333,0.181528,0.106220,0.758041,0.105303,NaN,...,0.705988,0.119310,NaN,NaN,0.651978,0.257727,NaN,NaN,-0.006329,0.219728
Academy Isd,4807470.0,48.0,5.289474,2011.842105,90.039474,0.098045,0.126701,0.854661,0.101134,NaN,...,0.813760,0.113339,NaN,NaN,NaN,NaN,0.361128,0.281480,0.047112,0.262791
"Academy, School District No. 20, In The County Of El Paso An",801920.0,8.0,5.500000,2013.000000,1724.166667,0.569399,0.036002,0.898520,0.027461,72.194444,...,0.884206,0.030713,-0.183872,0.146135,0.632741,0.148037,0.307499,0.085427,-0.112218,0.063473
Acadia Parish,2200030.0,22.0,5.500000,2012.000000,734.238095,-0.266876,0.047327,0.888729,0.035278,NaN,...,0.860905,0.039534,NaN,NaN,0.626577,0.089432,NaN,NaN,-0.162028,0.085081
Accomack Co Pblc Schs,5100060.0,51.0,5.000000,2012.000000,373.428571,-0.067904,0.065075,0.889180,0.054768,NaN,...,0.887532,0.089009,NaN,NaN,0.656624,0.132672,0.433049,0.172384,-0.073074,0.122758
Achille,4002370.0,40.0,5.493506,2011.896104,24.311688,-0.279143,0.208850,0.846051,0.016041,NaN,...,0.843048,0.018165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ackerman Elementary,601680.0,6.0,5.177419,2011.774194,55.661290,0.152426,0.155398,0.902752,0.136241,NaN,...,0.931368,0.031057,NaN,NaN,NaN,NaN,NaN,NaN,-0.207695,0.308554
Acton,2501680.0,25.0,4.511111,2011.333333,372.311111,0.966067,0.060971,0.822284,0.055005,99.933333,...,0.757400,0.059101,-0.640146,0.164980,NaN,NaN,NaN,NaN,-0.228143,0.116016
Acton School Department,2302220.0,23.0,5.617647,2011.411765,28.161765,0.146061,0.195464,0.866924,0.014157,NaN,...,0.861814,0.015895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yough Sd,4221150.0,42.0,5.500000,2012.000000,169.726190,0.128510,0.091437,0.892682,0.091866,NaN,...,0.893227,0.093593,NaN,NaN,NaN,NaN,NaN,NaN,-0.197190,0.178111
Youngstown City Schools,3904516.0,39.0,5.469880,2011.963855,604.626506,-0.696438,0.053652,0.894525,0.044474,NaN,...,0.980801,0.112821,NaN,NaN,0.253950,0.136223,0.228434,0.178915,-0.145141,0.097292
Yreka Union Elementary,643380.0,6.0,5.177419,2011.774194,101.693548,-0.245785,0.107474,0.879740,0.104138,NaN,...,0.859844,0.128842,NaN,NaN,NaN,NaN,0.153108,0.255078,-0.088792,0.220930
Ysleta Isd,4846680.0,48.0,5.289474,2011.842105,3219.763158,-0.068010,0.034339,0.864713,0.023516,21.000000,...,0.828292,0.084216,-0.752875,0.325597,0.272100,0.183729,0.258661,0.106423,-0.077206,0.056806
Yuba City Unified,643470.0,6.0,5.177419,2011.774194,1018.564516,-0.200459,0.049245,0.960506,0.040152,173.500000,...,0.972774,0.066170,-0.055613,0.115910,0.474562,0.223114,0.400200,0.095129,-0.119199,0.085402
Yuba County Office Of Education,691048.0,6.0,7.600000,2014.000000,25.200000,-1.086342,0.241048,0.906581,0.017846,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yucaipa-Calimesa Joint Unified,643560.0,6.0,5.177419,2011.774194,732.096774,-0.210640,0.053678,0.961714,0.045831,23.111111,...,0.945767,0.058337,-0.445521,0.262433,0.476311,0.249962,0.442821,0.097255,-0.179363,0.095393
Yukon,4033480.0,40.0,5.439024,2011.987805,556.987805,0.074511,0.050868,0.871140,0.043550,21.500000,...,0.852413,0.047509,-0.299099,0.261473,0.462470,0.228466,0.394542,0.168448,-0.023181,0.095874
Yukon Flats School District,200775.0,2.0,5.500000,2011.909091,24.613636,-1.126223,0.231736,0.959528,0.025624,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yukon/Koyukuk School District,200862.0,2.0,5.616667,2011.133333,94.200000,-0.363164,0.125317,1.042024,0.123183,NaN,...,1.046187,0.149968,NaN,NaN,NaN,NaN,NaN,NaN,-0.228300,0.235535
Yuma 1 School District,800016.0,8.0,5.459459,2013.054054,58.189189,0.037152,0.137617,0.878151,0.115856,NaN,...,0.875903,0.017194,NaN,NaN,NaN,NaN,0.591751,0.273202,-0.309053,0.279168
Yuma Elementary District,409600.0,4.0,5.500000,2012.000000,1171.345238,-0.335621,0.045817,0.975378,0.037628,21.583333,...,0.971548,0.066044,-0.087063,0.287399,0.331596,0.216974,0.479434,0.090599,-0.188786,0.081797
Yupiit School District,200004.0,2.0,5.578947,2011.894737,35.342105,-1.704323,0.212450,0.956792,0.026135,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.082793,0.344118
Yutan Public Schools,3179080.0,31.0,5.500000,2012.727273,33.787879,0.367202,0.179294,0.835797,0.017510,NaN,...,0.823126,0.018684,NaN,NaN,NaN,NaN,NaN,NaN,-0.129782,0.323996
Zachary Community School District,2200039.0,22.0,5.500000,2012.000000,388.380952,0.328938,0.059429,0.878620,0.045814,NaN,...,0.848773,0.062597,NaN,NaN,0.547706,0.108312,NaN,NaN,-0.154492,0.109894
Zalma R-V,2932490.0,29.0,5.268293,2011.926829,22.414634,-0.005135,0.219749,0.873592,0.015702,NaN,...,0.867309,0.016001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zane Trace Local,3904954.0,39.0,5.469880,2011.963855,117.192771,0.038858,0.099128,0.884322,0.088998,NaN,...,0.882669,0.090167,NaN,NaN,NaN,NaN,NaN,NaN,-0.089881,0.193362
Zaneis,4033540.0,40.0,4.896552,2012.068966,26.137931,-0.062731,0.203544,0.843792,0.016545,NaN,...,0.865571,0.019252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zanesville City,3904517.0,39.0,5.469880,2011.963855,267.674699,-0.316606,0.071485,0.931167,0.063265,NaN,...,0.959172,0.076623,NaN,NaN,0.347930,0.201853,NaN,NaN,-0.108784,0.137254
Zapata County Isd,4846710.0,48.0,5.289474,2011.842105,251.578947,-0.415031,0.080379,0.923201,0.068647,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.147183,0.155902
Zavalla Isd,4846740.0,48.0,5.289474,2011.842105,33.986842,-0.091842,0.207732,0.870556,0.016529,NaN,...,0.846327,0.016987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zeeland Public Schools,2636660.0,26.0,5.500000,2012.000000,421.488095,0.151476,0.061237,0.848983,0.056520,23.892857,...,0.830764,0.062817,0.158142,0.260265,NaN,NaN,0.539745,0.169626,-0.065606,0.115149
Zeigler-Royalton Cusd 188,1743800.0,17.0,5.500000,2012.000000,47.761905,-0.381677,0.151547,0.841837,0.055139,NaN,...,0.854488,0.038520,NaN,NaN,NaN,NaN,NaN,NaN,-0.106565,0.304590
Zephyr Isd,4846770.0,48.0,5.409091,2011.818182,23.227273,-0.135214,0.251966,0.864724,0.015028,NaN,...,0.840150,0.016195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zillah School District,5310170.0,53.0,5.500000,2011.000000,105.300000,-0.251525,0.101438,0.819970,0.104398,NaN,...,0.833479,0.106306,NaN,NaN,NaN,NaN,0.518367,0.215644,-0.104826,0.206678
Zion,4033600.0,40.0,5.407407,2011.975309,31.061728,-0.093082,0.186385,0.843651,0.016095,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zion Esd 6,1743860.0,17.0,5.500000,2012.000000,280.666667,-0.443680,0.067488,0.857369,0.054711,NaN,...,0.880593,0.014603,NaN,NaN,0.571670,0.221766,0.243512,0.222654,-0.110015,0.128495
Zionsville Community Schools,1802830.0,18.0,5.500000,2012.000000,455.476190,0.732508,0.057511,0.838033,0.055544,20.952381,...,0.825542,0.058511,-0.172836,0.284422,NaN,NaN,0.037757,0.237159,-0.111572,0.108633
Zumbrota-Mazeppa School District,2745735.0,27.0,5.500000,2012.000000,79.880952,0.554598,0.122499,0.831254,0.121827,NaN,...,0.820830,0.126440,NaN,NaN,NaN,NaN,NaN,NaN,-0.125769,0.241771
Zuni Public Schools,3502800.0,35.0,5.500000,2012.000000,89.035714,-0.773576,0.117687,0.758469,0.083410,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.188187,0.249357

## DropNA (any)
Removing rows with __any__ NA's from the Dataset

### 53939 Rows
This shrinks the dataset a bit, but this may not be a great approach as we lose Vermont in the process, for some reason...

In [12]:
dropna_any_geodist_long_CS= geodist_long_CS.dropna()

print(len(dropna_any_geodist_long_CS))

53939

In [13]:
dropna_any_geodist_long_CS.describe()

,leaidC,fips,grade,year,totgyb_all,mn_all,mn_all_se,sd_all,sd_all_se,totgyb_asn,...,sd_wht,sd_wht_se,mn_wag,mn_wag_se,mn_wbg,mn_wbg_se,mn_whg,mn_whg_se,mn_mfg,mn_mfg_se
count,5.393900e+04,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,...,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000,53939.000000
mean,2.736711e+06,27.238547,5.386214,2011.870520,2175.445003,0.075444,0.045429,0.955857,0.039191,159.523554,...,0.927432,0.058363,-0.171360,0.188601,0.654928,0.134959,0.530393,0.120747,-0.120325,0.081534
std,1.645820e+06,16.461001,1.686673,1.910837,3855.468725,0.363888,0.013930,0.098050,0.015023,590.110475,...,0.114938,0.031296,0.391058,0.076044,0.279434,0.058193,0.269755,0.050037,0.152668,0.027548
min,1.000070e+05,1.000000,3.000000,2009.000000,117.000000,-1.640004,0.010884,0.151321,0.008526,20.000000,...,0.089782,0.007768,-3.338188,0.027087,-0.565538,0.024387,-0.817202,0.024097,-0.924556,0.020913
25%,1.200300e+06,12.000000,4.000000,2010.000000,749.000000,-0.172056,0.035537,0.890946,0.028886,34.000000,...,0.851403,0.038032,-0.415247,0.132304,0.471310,0.088038,0.348452,0.081808,-0.229931,0.062176
50%,2.725200e+06,27.000000,5.000000,2012.000000,1281.000000,0.084195,0.043444,0.950719,0.036758,61.000000,...,0.918070,0.050942,-0.190925,0.186145,0.636131,0.124249,0.504586,0.110471,-0.120076,0.077244
75%,4.205400e+06,42.000000,7.000000,2013.000000,2302.000000,0.319917,0.053229,1.014955,0.046749,127.000000,...,0.990846,0.069692,0.043378,0.234024,0.818099,0.176910,0.688122,0.153733,-0.006671,0.096009
max,5.601980e+06,56.000000,8.000000,2015.000000,76330.000000,1.627928,0.178311,1.670542,0.184316,12214.000000,...,2.092118,0.454513,2.376060,1.863152,2.460451,0.949624,2.302626,0.500565,0.765343,0.396787

In [14]:
print(len(dropna_any_geodist_long_CS["stateabb"].value_counts()))
print(dropna_any_geodist_long_CS["stateabb"].value_counts().sort_index())

50
AK     198
AL     466
AR     412
AZ    2019
CA    7950
CO     517
CT    1220
DC      73
DE     420
FL    1668
GA    1725
HI      84
IA     607
ID     138
IL    2442
IN     872
KS     453
KY     413
LA     689
MA    1278
MD     971
ME      58
MI    1296
MN    2049
MO    1191
MS     248
MT      25
NC    1662
ND      51
NE     242
NH      91
NJ    3529
NM     258
NV     123
NY    1965
OH    1096
OK     959
OR     542
PA    1892
RI     235
SC    1107
SD      62
TN     814
TX    5067
UT     592
VA    1203
WA    1705
WI    1222
WV      28
WY      12
Name: stateabb, dtype: int64

## DropNA (ALL)
Removing rows where __all__ values are NA

### 825816 Rows

In [15]:
dropna_all_geodist_long_CS= geodist_long_CS.dropna(how="all",subset=quant_cols)

print(len(dropna_all_geodist_long_CS))

825816

In [16]:
print(len(dropna_all_geodist_long_CS["stateabb"].value_counts()))
print(dropna_all_geodist_long_CS["stateabb"].value_counts())

51
TX    63016
IL    56071
OH    49847
CA    45425
PA    41698
MI    41408
NY    40473
NJ    32655
WI    31639
MO    31020
OK    29408
MN    25410
IA    25245
IN    24082
MA    20854
AR    18426
KS    16040
GA    15035
KY    14284
WA    12916
AZ    12056
MS    11811
TN    11041
AL    10989
CT    10742
OR    10411
NE    10265
NC     9680
NH     9226
ME     8823
VT     7441
VA     7360
SC     7046
SD     6696
ID     6159
MT     6132
LA     6084
NM     5587
FL     5336
ND     4767
CO     4619
WV     4372
UT     3002
AK     2601
RI     2536
WY     1856
MD     1845
DE     1299
NV      916
HI       84
DC       82
Name: stateabb, dtype: int64

In [17]:
dropna_all_geodist_long_CS.describe()

,leaidC,fips,grade,year,totgyb_all,mn_all,mn_all_se,sd_all,sd_all_se,totgyb_asn,...,sd_wht,sd_wht_se,mn_wag,mn_wag_se,mn_wbg,mn_wbg_se,mn_whg,mn_whg_se,mn_mfg,mn_mfg_se
count,8.258160e+05,825816.000000,825816.000000,825816.000000,825814.000000,825814.000000,825814.000000,825814.000000,825814.000000,85523.000000,...,733460.000000,733460.000000,84024.000000,84024.000000,164413.000000,164413.000000,196243.000000,196243.000000,658277.000000,658277.000000
mean,3.003463e+06,29.903256,5.439089,2011.844344,328.138101,0.045220,0.112220,0.876175,0.069390,122.689382,...,0.865864,0.072814,-0.220768,0.208535,0.597313,0.167170,0.461360,0.171250,-0.123905,0.182086
std,1.457768e+06,14.573536,1.694571,1.959203,1166.280140,0.400055,0.054619,0.121183,0.044821,483.938421,...,0.121514,0.048231,0.413746,0.086235,0.283890,0.063211,0.288484,0.064866,0.245448,0.074982
min,1.000020e+05,1.000000,3.000000,2009.000000,20.000000,-3.186861,0.010884,0.042187,0.007450,20.000000,...,0.073921,0.007754,-3.534657,0.027087,-0.732104,0.024387,-1.300542,0.024097,-3.015474,0.020913
25%,1.809690e+06,18.000000,4.000000,2010.000000,55.000000,-0.205949,0.070441,0.807569,0.029866,29.000000,...,0.797136,0.024112,-0.469659,0.150712,0.414415,0.118164,0.272639,0.120955,-0.275129,0.123825
50%,2.930660e+06,29.000000,5.000000,2012.000000,119.000000,0.049993,0.099618,0.873354,0.066962,47.000000,...,0.860279,0.071799,-0.234257,0.206814,0.582891,0.166099,0.445352,0.170093,-0.120150,0.172847
75%,4.106300e+06,41.000000,7.000000,2013.000000,277.000000,0.300706,0.149012,0.940343,0.097356,97.000000,...,0.926429,0.102897,0.010506,0.251811,0.762919,0.212231,0.636042,0.216630,0.031581,0.237248
max,5.606240e+06,56.000000,8.000000,2015.000000,76800.000000,3.804560,1.841295,4.186017,1.416418,12214.000000,...,3.830692,1.672288,3.670907,2.130670,3.913644,1.320550,4.076381,1.328091,1.739556,1.715452

In [18]:
dropna_all_geodist_long_CS.head()

,leaidC,leaname,fips,stateabb,grade,year,subject,totgyb_all,mn_all,mn_all_se,...,sd_wht,sd_wht_se,mn_wag,mn_wag_se,mn_wbg,mn_wbg_se,mn_whg,mn_whg_se,mn_mfg,mn_mfg_se
0,100002,Alabama Youth Services,1,AL,8,2009,ela,29.0,-1.569190,0.209354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,Alabama Youth Services,1,AL,8,2009,math,36.0,-1.761643,0.206164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100002,Alabama Youth Services,1,AL,8,2011,ela,29.0,-0.962804,0.203069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100002,Alabama Youth Services,1,AL,8,2011,math,27.0,-1.641117,0.223450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100002,Alabama Youth Services,1,AL,8,2012,ela,33.0,-1.069076,0.190945,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN